version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: safe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: safe_user
      POSTGRES_PASSWORD: safe_password
      POSTGRES_DB: safe_accident_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: safe-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  postgres_data: